joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster
    publish_rate: 50

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller
    left_wheel_names: ["rear_left_wheel_joint", "front_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint", "front_right_wheel_joint"]
    publish_rate: 50